### ISSUE TITLE
ez-streams package on npm doesn't have the lib/ folder generated

### ISSUE THREAD

**Issue by roblabla** [Sage/ez-streams#37]
Hey,

Just wanted to let you know the current version of ez-streams on npm probably failed to run the prepublish script, since the lib/ folder is missing.

**Comment by bjouhier** [comment]
Thanks for reporting. The problem came from the `.gitignore` file. I created a `.npmignore` to have different exclusion lists in git and npm.

I bumped the version to 1.2.0 because this new version includes an API change: the `stop` method is now asynchronous: `stop(_, arg)` instead of `stop(arg)`
