### ISSUE TITLE
Broken LInks in API Reference

### ISSUE THREAD

**Issue by cj10** [Sage/ez-streams#40]

**Comment by cj10** [comment]
The first link in API.md is labelled \[ez-streams/src/devices/array\], but actually points to https://github.com/Sage/ez-streams/blob/master/lib/devices/array.md. The intended file really resides at https://github.com/Sage/ez-streams/blob/master/src/devices/array.md. All of the links in API.md are broken in a similar way.

**Comment by cj10** [comment]
@bjouhier, you brought streamline.js to my attention by mentioning it in https://github.com/oracle/node-oracledb/issues/115#issuecomment-154370232. I had not previously seen it. I am now fascinated. Thank you!

**Comment by bjouhier** [comment]
@cj10 Welcome and thanks. I will fix the links. I recently moved `lib` to `src` and forgot to update.

If you work with oracle you may want to have a look at [ez-oracle](https://github.com/Sage/ez-oracle/blob/master/lib/index.md). This satellite package is still experimental and not properly documented but the source code gives an idea on how `ez-streams` can be used with Oracle.

Bruno
